language: node_js
node_js:
  - "stable"
cache: npm
script:
  - npm test
  - npm run cov
  - npm run build
notifications:
  email:
    recipients:
      - just4ink007@gmail.com
    on_success: never
    on_failure: always